dist: trusty
language: java
addons:
  sonarcloud:
    organization: kencrisjohn
    token:
      secure: wtnnl3Q5VdKXCD2gP+Un4ONLQkTlf0P/AvuBljAW7AcTsri8ynEFQHqn8y5UdBMaihTF+5yaYc5PHRe3ZI8bIuED0UwO76a/+echNE3EjPNYZ2IZ0jIBsIORn0XoODn7BjEjooYoVwWL5+4ubBgmkyBXSuDco7eH0A2SO4v2PBhnK/Bimt/o7mFOLQT3GbFl+ZzoN7QrfkLmsS8Q5Oj29mbsv5J/wt17uAxnzt0uFQHcRSeE4io8UUJAkFNfaHm2juf3wIbW2ZlUSbKfkWdmpV28tfw+WvbI3StQ5lcIq9xUTYH9QAS9OW13d19eiy0gjHgd/OmF0FuPze2Sl5nR1GVCWubeBI2I0hMB15pfqw0athjqBSznGtWP/j/QD/ZkmkpVsXN7CgLPGkZYIMq33lF4WNWHn2cLZOZkV0k+algVBlt7TwpB0Ytl+MwIEK1FpDa6VNqfzUBoj3ukXwo1KdaEUgNydPF5NdqcjlhyNmOdoQhYWLrrVU3TDJX+QFN4QwbTP5mPix/aNW/LsHS7+HGMrKhZR7rJIfZUg5k+CiGLOVIqn49CKCSsi8sb7w5SSiqIJ5ZzhSabfsLNgAOJSeVyTRYGu4ov3Kih69aMYjZk4Q4fYhVMm1sPU7hLl9sZfM0GYftFEll7yqMdo/4nYlgiPy9k/BVfobxbB+D6E7A=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: CK2GAQBwne1cBdx39fN4+f+qSOYy5mA1wf3JHESwVrRLpyxayhOco91YhwgbQWqX9RHfnxqCWtNz6KzP+vnoVv0+ulyDqZdGPMOqcsqv4yHXoP/XLApHdsOc5FU25UtoRsoCwSiE9XERdk8wCu7Op8hGQ+xbt/1N6/g/e1DNont21tBWMToG1SOZUkV/m6b5rr0XkS3EDEZ9kwbTIKRaT4tEyP7Lh765wbl4q0UGZOqSrXwRPOl2HbnDdQmhS0EZcq6XGK5iMfthSwgG749AYHuAI9IOUerQOT6Kn7ALxIPXGdpdS5dGVVBplI5r8w6GonYWvL9FDXVtePZK6/8CfB0kusPGswIJ3uMYNC/6ZTbh0iWsEc5jkfXwH6qDWu5gGrKk3W7YYoOkdkkHd/zbQmvj5hCJlEcyV6UroqDCdaB+DguTZZ8N9QD4TF3Tx68TsrRlRbBEZ8wLDO3M1xJn047l9+K4bubGAN+WrcFCaaY1seGZ4AlIk3VzUnhy/Qvl44b4m+XS+XOpBVj52+aIbW2jpDWotRtryjwFxtk2DxgXj4FTLlsIiO3RgrZLehgR5cPXD3aooplHjC70esKImul53HPVjFO0+MSEsrqKrYcPlmZwS252FiizcRDMOe/ZSpaM7zntnJ8HmUZ0fvByElocg2TkK1CJyOtV1NtTVf8=
  app: spring-psx-api
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_351f39d4ee6c_key -iv $encrypted_351f39d4ee6c_iv
  -in secrets.tar.enc -out secrets.tar -d
- chmod +x mvnw
- tar xvf secrets.tar
cache:
  directories:
  - "$HOME/.m2/"
