dist: trusty
language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: W6E8jnMmPlNj4xAqeGgbIeuX1q+xHgIkDSdQA3iDpfNPudP3Z81/nKIH3CdeDhg83Cw5s8bATrv2M+EHk26SI+Acl1KQhA29JcnyDoo9SGSNYPBr0DcYqT2S2/5e/H4ktDyBZhDQxOxBu7F1n/rfeg5h84mtFDWB7lUIDo/piJNxnvxibfN0gYpEMiUu+bblr7fqVeCFMZr3fb096c3WT/OjoE87DuasA3Auptyl8l5y3ckA0vi81dYOtMPZZp07Eux/McOO324q+R8S0938fgdxCx+2wopc8QxEv78Ozq73iJGYFa/Ekhy4RVH/N2ziuvEtw4ATxK4sanpUdAPvvjc+CXR7cItinUQlkmtG1F/NGdsGC0GniCCfkSlQk/KvyVFJNZAq4iKukeskJWcazOwxZU9FisdaSam0EsjEWrhG3ETVsf5qeH494f67hutH0TGH69hOqCAFYQVXM1Y9nQ1KGhI2tNdN86jKTx/wVdkhrO3IHsL96vW41q1pKHNxlZs1lQf/T6BFyblrz9Ok6TonnXg8oKr0YCh1HJg1XgZ5ZnZqEksm5hhhKLH/nqNWeIEmZ0hjaqJ83MuVsbdxtEPEX/5PSNnJYkf3+egigIU0XN2CrNyz4yZLQqriCVw1iC89ZTE8AB9EzUUHIZ/86XsIXcvI996d5t72yhgknFI=
  app: spring-psx-api
before_install:
- chmod +x mvnw
