dist: trusty
language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: EBtnJOJYlP6cNTANkcyCmaqGUWlD7dvu6gDwyhz7l0n8NS9VrIQK1m+SQZx9AiR5zywIx4xilXIc94Kr6qCJUzJQ+/9rYI5U+2Fb7Qfkc6mTTEkygUzouKh5+WbBLNlOFi4Z3Ulx1vPr6+D/eQQTyxFJ18+l9gJkODLdCNs+f2ZFjH+eLd4xvFVIfAflu1lV35rqQ/REz1KaJ9OEf8AKnK/QAbRRF8i+8XvPxaCw0BXXKT3njQkk/Ru1CTOv9+Gze7/vMRRqDICLJgnkXQ8iM650dJySWmxByJlFwVA7LRSPxkF0kYwkStmckAoQJni7yCNVlHKBfMJDF6nMzttj5zNjvhQ/aaxxdkRNTXPkWMNpL/hrsw2XH7u7WBrQ2iOKnB4hoP8pN3XLySm2QHGE5e+za3kpreYrTj7K9xxnWLAddu9EFT9Rk/Uz/s9zuPvlY5Ez+0mI8Wp1jX5r6Nq3Dvtd6DlcRzEBAetxQ6jRCTnuhDiuin4oYdnz8A0blhp+GCRQu2JcXasMXmAsGYeSp1KBd16gWl3WV65B2FjPyx3AckSNMFoRwRcTkz+vvRVqb32p0uEJE0Z49pc4S2ySegHSkK1fm9Zq51Ujp/K1SOKMLvb5KzarOsJXT3vfaXG8JKRSW1n3jPjqAmtdqhxfvhCO8p9xaqQ6NFbKXQ2rITg=
  app: spring-psx-api
before_install:
  - chmod +x mvnw