spring:
  application:
    name: spring-psx-api
  profiles:
    active: ${SPRING_PROFILE:local}
  sleuth:
    sampler:
      probability: 1
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop


server:
  port: ${PORT:8082}